/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author bruno.schneider
 */
public class AdmTela extends javax.swing.JFrame {

    /**
     * Creates new form AdmTeLA
     */
    public AdmTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        iconCaixa = new javax.swing.JLabel();
        iconWatchguard = new javax.swing.JLabel();
        iconFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Instalar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        iconCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/caixa.png"))); // NOI18N
        iconCaixa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconCaixaMouseClicked(evt);
            }
        });
        getContentPane().add(iconCaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        iconWatchguard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/watchguardLogo.png"))); // NOI18N
        getContentPane().add(iconWatchguard, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        iconFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Pfundo3.png"))); // NOI18N
        iconFundo.setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().add(iconFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            java.awt.Desktop.getDesktop().open(new File("Y:\\Software\\Instalacao Padrao"
                    + "\\Instalação Administração\\01 - WatchGuard\\WG-Authentication-Client_12_5_4.msi"));
        } catch (IOException ex) {
            Logger.getLogger(AdmTela.class.getName()).log(Level.SEVERE, null, ex);
        }
        iconCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/caixaMarcada.png")));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void iconCaixaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconCaixaMouseClicked
        if(iconCaixa.getIcon().equals(getClass().getResource("/imgs/caixaMarcada.png"))){
            iconCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/caixa.png")));
            
        }else if(iconCaixa.getIcon().equals(getClass().getResource("/imgs/caixa.png"))){
            iconCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/caixaMarcada.png")));
        }
    }//GEN-LAST:event_iconCaixaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdmTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdmTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdmTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdmTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdmTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconCaixa;
    private javax.swing.JLabel iconFundo;
    private javax.swing.JLabel iconWatchguard;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
