
package view;

import javax.swing.ImageIcon;

/**
 *
 * @author bruno.schneider
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        iconSaude = new javax.swing.JLabel();
        iconAdm = new javax.swing.JLabel();
        iconEdu = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconSaude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/iconSaudeSeco.png"))); // NOI18N
        iconSaude.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iconSaudeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iconSaudeMouseExited(evt);
            }
        });
        getContentPane().add(iconSaude, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 250, -1));

        iconAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/iconAdmSeco.png"))); // NOI18N
        iconAdm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                iconAdmMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iconAdmMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iconAdmMouseExited(evt);
            }
        });
        getContentPane().add(iconAdm, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 250, 70));

        iconEdu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/iconEduSeco.png"))); // NOI18N
        iconEdu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                iconEduMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                iconEduMouseExited(evt);
            }
        });
        getContentPane().add(iconEdu, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 250, 70));

        jPanel1.setOpaque(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Pfundo2.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 520, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void iconEduMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconEduMouseEntered
        iconEdu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/iconEduMolhado.png")));
    }//GEN-LAST:event_iconEduMouseEntered

    private void iconEduMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconEduMouseExited
        iconEdu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/iconEduSeco.png")));
    }//GEN-LAST:event_iconEduMouseExited

    private void iconAdmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconAdmMouseEntered
        iconAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/iconAdmMolhado.png")));
    }//GEN-LAST:event_iconAdmMouseEntered

    private void iconAdmMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconAdmMouseExited
        iconAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/iconAdmSeco.png")));

    }//GEN-LAST:event_iconAdmMouseExited

    private void iconSaudeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconSaudeMouseEntered
        iconSaude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/iconSaudeMolhado.png")));
    }//GEN-LAST:event_iconSaudeMouseEntered

    private void iconSaudeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconSaudeMouseExited
        iconSaude.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/iconSaudeSeco.png")));
    }//GEN-LAST:event_iconSaudeMouseExited

    private void iconAdmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_iconAdmMouseClicked
        AdmTela admT = new AdmTela();
        admT.setVisible(true);
        if (admT.isVisible()){
            this.dispose();
        }
    }//GEN-LAST:event_iconAdmMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconAdm;
    private javax.swing.JLabel iconEdu;
    private javax.swing.JLabel iconSaude;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
